<?php
/**
 * Return the default options of the theme
 * 
 * @return  void
 */

function themesflat_customize_default($key) {
	$default = array(
		'social_links'	=> array ("facebook-f" => '#', "twitter" => '#' , "instagram" => '#', "youtube" => '#'),
		'show_social_share' => 0,
		'go_top' => 1,
		'enable_smooth_scroll'	=> 0,
		'enable_preload' => 1,
		'preload' => 'preload-6',
		//topbar
		'topbar_background_color'	=> '#F8F8F8',
		'topbar_textcolor'	=> '#091D3E',
		'topbar_link_color' => '#091D3E',
		'topbar_link_color_hover' => '#33B9CB',		
		'topbar_address_label' => '<i class="grower-icon-map-marker-alt11"></i>',
		'topbar_address' => '2072 Pinnickinick Street, WA 98370',
		'topbar_email_label' => '<i class="grower-icon-envelope1"></i>',
		'topbar_email' => 'info@website.com',
		'topbar_time_label' => '<i class="grower-icon-clock1"></i>',
		'topbar_time' => 'Sun - Monday, 08:00 am - 09:00 pm',
		'social_topbar' => 1,
		'typography_topbar' => array(
			'family' => 'Rubik',
			'style'  => '500',
			'size'   => '14',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'topbar_controls' => array('padding-top' => 16,'padding-bottom' => 16),
		//Header
		'style_header'	=> 'header-default',	
		'header_backgroundcolor'=>'#ffffff',
		'header_sticky' => 0,
		'header_search_box' => 0,
		'header_content_right' => '',
		'header_absolute'	=> 0,		
		'header_sidebar_toggler' => 0,
		'header_button_text' => '',
		'header_button_url' => '',
		'header_info_phone_text' => '',
		'header_info_phone_number' => '',
		'show_post_navigator' => 0,
		'show_entry_footer_content'	=> 1,
		'logo_width' => 196,
		'menu_location_primary' => 'primary',
		'site_logo'	=> THEMESFLAT_LINK . 'images/logo.png',
		'site_logo_mobile'	=> THEMESFLAT_LINK . 'images/logo.png',	
		'show_bottom' => 1,		
		'header_backgroundcolor_sticky'=>'#ffffff',		
		'primary_color'=>'#091D3E',
		'secondary_color'=>'#33B9CB',
		'accent_color'=>'#091D3E',
		'typography_body' => array(
			'family' => 'Rubik',
			'style'  => 'regular',
			'size'   => '16',
			'line_height'=>'1.9',
			'letter_spacing' => '',
		),
		'body_text_color'=>'#565872',
		'body_background_color' => '',
		'page_sidebar_layout' => 'fullwidth',
		'content_controls' => array('padding-top' => 80,'padding-bottom' => 80),
		'typography_menu' => array(
			'family' => 'Rubik',
			'style'  => '500',
			'size'   => '18',
			'line_height'=>'120px',
			'letter_spacing' => '',
		), 
		'mainnav_color'		=> '#091D3E',
		'mainnav_hover_color'=>'#33B9CB',
		'mainnav_active_color'=>'#33B9CB',
		'menu_distance_between' => 0,
		'typography_sub_menu' => array(
			'family' => 'Rubik',
			'style'  => '500',
			'size'   => '18',
			'line_height'=>'1.3',
			'letter_spacing' => '',
		),
		'sub_nav_color'		=>'#091D3E',		
		'sub_nav_color_hover'	=>	'#33B9CB',
		'sub_nav_background'=>'#ffffff',
		'sub_nav_background_hover'=>'#F8F8F8',
		'sub_nav_border_color' => '#E8E8E8',
		'typography_headings'	=> array(
			'family' => 'Jost',
			'style'  => '700',
			'line_height'=>'1.2',
			'letter_spacing' => ''		
		),
		'h1_size' => 55,
		'h2_size' => 46,
		'h3_size' => 32,
		'h4_size' => 28,
		'h5_size' => 24,
		'h6_size' => 20,
		'typography_blockquote' => array(
			'family' => 'Rubik',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'30px',
			'letter_spacing' => '',
		),	
		'typography_blog_post_title' => array(
			'family' => 'Jost',
			'style'  => '500',
			'size'   => '32',
			'line_height'=>'1.2',
			'letter_spacing' => '-0.6px',
		),
		'typography_blog_post_meta' => array(
			'family' => 'Rubik',
			'style'  => '500',
			'size'   => '14',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'typography_blog_post_buttons' => array(
			'family' => 'Rubik',
			'style'  => '500',
			'size'   => '15',
			'line_height'=>'1',
			'letter_spacing' => '',
		),
		'typography_blog_single_title' => array(
			'family' => 'Jost',
			'style'  => '500',
			'size'   => '32',
			'line_height'=>'1.2',
			'letter_spacing' => '-0.6px',
		),
		'typography_blog_single_comment_title' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '35',
			'line_height'=>'1.2',
			'letter_spacing' => '',
		),
		'typography_sidebar_widget_title' => array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '20',
			'line_height'=>'1.2',
			'letter_spacing' => '',
		),			
		//Page Title
		'page_title_styles' => 'default',
		'page_title_alignment' => 'left',
		'page_title_video_url' => THEMESFLAT_PROTOCOL . '://www.youtube.com/watch?v=JyMeGpvpjas',
		'typography_page_title'	=> array(
			'family' => 'Jost',
			'style'  => '700',
			'size'   => '46',
			'line_height'=>'1.2',
			'letter_spacing' => '',
		),
		'page_title_background_color' => '#dceaeb',
		'page_title_background_color_opacity' => '60',
		'page_title_text_color' => '#091D3E',		
		'page_title_controls' => array('padding-top' => 155, 'padding-bottom' => 168),
		'page_title_background_image' => '',
		'page_title_image_size' => 'auto',
		'page_title_heading_enabled' => 1,
		'typography_breadcrumb'	=> array(
			'family' => 'Rubik',
			'style'  => '400',
			'size'   => '18',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'bread_crumb_prefix' =>'',
		'breadcrumb_separator' =>  wp_kses( '<i class="grower-icon-chevron-right"></i>', themesflat_kses_allowed_html() ),
		'breadcrumb_color' => '#091D3E',
		'typography_buttons' => array(
			'family' => 'Rubik',
			'style'  => '500',
			'size'   => '15',
			'line_height'=>'1',
			'letter_spacing' => '',
		),
		'typography_pagination'	=> array(
			'family' => 'Rubik',
			'style'  => '400',
			'size'   => '20',
			'line_height'=>'1',
			'letter_spacing' => '',
		),		
		'typography_bottom_menu' => array(
			'family' => 'Rubik',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'breadcrumb_enabled' => 1,
		//Blog
		'show_post_paginator' => 0,
		'blog_grid_columns' => 2,
		'post_content_elements' => 'meta,title,excerpt_content,readmore',
		'meta_elements' => 'author,date',
		'blog_archive_exclude' => '',
		'blog_featured_title' => '',
		'sidebar_layout' => 'sidebar-right',
		'blog_archive_layout' => 'blog-list',
		'related_post_style'	=> 'blog-grid',
		'grid_columns_post_related' => 2,
		'number_related_post' => 2,
		'blog_sidebar_list'		  => 'blog-sidebar',	
		'blog_archive_readmore' => 1,
		'blog_archive_post_excepts_length' => 27,
		'blog_archive_readmore_text' => 'Read More',
		'blog_archive_pagination_style' => 'pager-numeric',
		'blog_posts_per_page'	=> 3,
		'blog_order_by'	=> 'date',
		'blog_order_direction' => 'DESC',
		'page_sidebar_list'	=> 'blog-sidebar',
		//Portfolio	
		'portfolio_slug' => '',
		'portfolio_name' => '',
		'portfolio_show_filter' => 0,
		'portfolio_grid_columns' => 3,
		'portfolios_number_post'=> 6,
		'portfolio_filter_category_order' => '',
		'portfolio_order_by' => 'date',
		'portfolio_order_direction' => 'DESC',
		'portfolio_exclude' => '',
		'portfolios_layout' => 'fullwidth',
		'portfolios_show_post_navigator' => 0,
		'portfolios_show_related' => 0,
		'portfolios_related_grid_columns' => 3,
		'portfolios_sidebar_list' => 'blog-sidebar',
		'number_related_post_portfolios' => 3,
		'portfolios_featured_title' => 'Portfolio Details',
		//Project
		'project_slug' => '',
		'project_name' => '',
		'project_show_filter' => 0,
		'project_grid_columns' => 3,
		'project_number_post'=> 9,
		'project_filter_category_order' => '',
		'project_order_by' => 'date',
		'project_order_direction' => 'DESC',
		'project_exclude' => '',
		'project_layout' => 'fullwidth',
		'project_show_post_navigator' => 0,
		'project_show_related' => 0,
		'project_related_grid_columns' => 3,
		'project_sidebar_list' => 'blog-sidebar',
		'project_featured_title' => 'Project Details',
		'number_related_post_project' => 3,
		//Services
		'services_slug' => '',
		'services_name' => '',
		'services_show_filter' => 0,
		'services_grid_columns' => 2,
		'services_number_post'=> 6,
		'services_archive_pagination_style' => 'pager-numeric',
		'services_filter_category_order' => '',
		'services_order_by' => 'date',
		'services_order_direction' => 'DESC',
		'services_exclude' => '',
		'services_layout' => 'fullwidth',
		'services_sidebar_list' => 'blog-sidebar',
		'services_show_post_navigator' => 0,
		'services_show_related' => 0,
		'services_related_grid_columns' => 3,
		'number_related_post_services' => 3,
		'services_featured_title' => 'Service Details',
		//Gallery
		'gallery_slug' => '',
		'gallery_name' => '',
		'gallery_show_filter' => 0,
		'gallery_grid_columns' => 3,
		'gallery_number_post'=> 6,
		'gallery_archive_pagination_style' => 'pager-numeric',
		'gallery_filter_category_order' => '',
		'gallery_order_by' => 'date',
		'gallery_order_direction' => 'DESC',
		'gallery_exclude' => '',
		'gallery_layout' => 'fullwidth',
		'gallery_sidebar_list' => 'blog-sidebar',
		//Doctor
		'doctor_slug' => '',
		'doctor_name' => '',
		'doctor_grid_columns' => 3,
		'doctor_number_post'=> 6,
		'doctor_archive_pagination_style' => 'pager-numeric',
		'doctor_order_by' => 'date',
		'doctor_order_direction' => 'DESC',
		'doctor_exclude' => '',
		'doctor_featured_title' => 'Doctor Details',
		//Footer
		'typography_footer' => array(
			'family' => 'Rubik',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'typography_footer_widget_title' => array(
			'family' => 'Jost',
			'style'  => '600',
			'size'   => '20',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'footer_background_color'	=> '#152847',
		'footer_title_widget_color' => '#ffffff',
		'footer_text_color'			=> '#ffffff',
		'footer_text_color_hover'   => '#33B9CB',
		'footer_widget_areas' => 5,
		'footer_controls' => array('padding-top' => 100, 'padding-bottom' => 100),
		'footer_style' => 'footer-style2',
		'footer1' => 'footer-1',
		'footer2' => 'footer-2',
		'footer3' => 'footer-3',
		'footer4' => 'footer-4',
		'footer5' => 'footer-5',
		'footer_background_image' => '',
		'footer_image_size' => 'auto',
		'typography_bottom_copyright' => array(
			'family' => 'Rubik',
			'style'  => '400',
			'size'   => '16',
			'line_height'=>'1.5',
			'letter_spacing' => '',
		),
		'bottom_style' => 'bottom-style1',
		'bottom_logo' => THEMESFLAT_LINK . 'images/logo-light.png',
		'bottom_background_color'	=> '#1c2f4d',
		'bottom_text_color'			=> '#ffffff',
		'bottom_link_color'         => '#ffffff',
		'bottom_text_color_hover'   => '#33B9CB',		
		'layout_version'			=> 'wide',		
		'footer_copyright'			=> '© Themesflat 2022 | all rights reserved',						
		'show_action_box'	=> 0,
		'action_box_style' => 'style2',
		'heading_action_box'	=>	'Enter Your Mail For subscribe',
		'text_action_box'	=>	'Learn more about our use of cookies cookie policy',
        'action_box_content_right'	=> '',
        'action_box_background_image' => '',
        'action_box_background_color' => '#33B9CB',
        'action_box_heading_color' => '#ffffff',
        'action_box_text_color'	=> '#ffffff',
        'action_box_button_text_color' => '#ffffff',
        'action_box_button_background_color' => '#091D3E',
        'action_box_controls' => array('padding-top' => '','padding-right' => '','padding-bottom' => '','padding-left' => ''),
        'show_partner'	=> 0,
		'img_partner' => '',
		'show_number_img_partner_desktop' => 6,
		'show_number_img_partner_tablet' => 4,
		'show_number_img_partner_mobile' => 2,
		'gap_img_partner' => 30,
		'partner_box_controls' => array('padding-top' => 60,'padding-bottom' => 60),
		'partner_box_background_color' => '',
        'show_footer_info'	=> 0,
        'footer_info_text_address' => '2416 Mapleview Drive',
        'footer_info_address' => 'Tampa, FL 33634',
        'footer_info_text_phone' => 'Office Telephone : 0029129102320',
        'footer_info_phone' => 'Mobile : 000 2324 39493',
        'footer_info_text_mail' => 'Main Email : contact@website.com',
        'footer_info_mail' => 'Inquiries : Info@mail.com',
        'footer_info_background' => 'rgba(0,146,255,0.1)',
        'footer_info_color_text' => '#ffffff',
        'footer_info_color_icon' => '#33B9CB',
        'footer_botom_button_title' 	=> 'GET A FREE QUOTE',
        'footer_botom_button_link' 	=> '#',
        'footer_botom_content' 		=> 'Now! Get a Free Consultation for Your Business',
	);
	return $default[$key];
}